version: '3'
services:
  keystore.adrianosela.com:
    image: keystore
    build: ../Keystore/
    ports:
     - "8080:80"
  idp-a.adrianosela.com:
    image: auth-image
    build: .
    ports:
     - "8081:80"
    environment:
     - IDP_ISSUER_URL=http://localhost:8081
    depends_on:
     - "keystore.adrianosela.com"
  idp-b.adrianosela.com:
    image: auth-image
    build: .
    ports:
     - "8082:80"
    environment:
     - IDP_ISSUER_URL=http://localhost:8082
    depends_on:
     - "keystore.adrianosela.com"
  idp-c.adrianosela.com:
    image: auth-image
    build: .
    ports:
     - "8083:80"
    environment:
     - IDP_ISSUER_URL=http://localhost:8083
    depends_on:
     - "keystore.adrianosela.com"
