version: '3'
services:
  keystore.adrianosela.com: #because I own adrianosela.com
    image: keystore
    build: ../Keystore/
    ports:
     - "8080:80"
  identity_provider_A:
    image: authservice
    build: .
    ports:
     - "8081:8888"
    depends_on:
     - "keystore.adrianosela.com"
  identity_provider_B:
    image: authservice
    build: .
    ports:
     - "8082:8888"
    depends_on:
     - "keystore.adrianosela.com"
  identity_provider_C:
    image: authservice
    build: .
    ports:
     - "8083:8888"
    depends_on:
     - "keystore.adrianosela.com"
